services:
  api:
    container_name: "todo-api"
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=tododb
      - DATABASE_USERNAME=developer
      - DATABASE_PASSWORD=developer
  db:
    container_name: "todo-db"
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=tododb
    volumes:
      - todos_volume:/var/lib/postgresql/data
      - ./utils/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
  adminer:
    image: adminer
    restart: always
    ports:
      - 9091:8080

volumes:
  todos_volume: {}
